# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=9)),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('alcohol_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Category')),
            ],
            options={
                'ordering': ['alcohol_price'],
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('alcohol_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.Product')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.AlterUniqueTogether(
            name='producthistory',
            unique_together=set([('product', 'timestamp')]),
        ),
    ]
