# Generated by Django 2.1.1 on 2018-09-12 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('guide', '0003_do_nothing_on_delete_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producthistory',
            options={'get_latest_by': 'timestamp', 'ordering': ['product', 'timestamp']},
        ),
    ]
